# syntax=docker/dockerfile:1
ARG RUBY_VERSION=3.3.6
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

# Dependencias básicas
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl build-essential libpq-dev git apt-transport-https \
    libvips postgresql-client && \
    # Node y Yarn para Rails 8
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs wkhtmltopdf && \
    npm install -g yarn && \
    rm -rf /var/lib/apt/lists/*

# Copiamos Gemfiles primero para caching
COPY Gemfile Gemfile.lock ./

ENV BUNDLE_PATH=/bundle \
    BUNDLE_JOBS=4 \
    BUNDLE_RETRY=3

RUN bundle install

# Copiamos el resto del proyecto
COPY . .

# Puerto de desarrollo
EXPOSE 3000

# Comando por defecto
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]